### ISSUE TITLE
log file can't be generated

### ISSUE THREAD

**Issue by technickid** [icarus-sim/hashrouting-icn13-results#2]
Hi,
when I run on ubuntu 12.04, python 2.7, it can't create log file.
I have try to change python to python2 in run.sh but it's not fixed.

ADDING ICARUS TO PYTHON PATH
CREATING DIRECTORIES FOR GRAPHS AND LOGS
EXECUTING SIMULATIONS
Traceback (most recent call last):
  File "run.py", line 12, in <module>
    from fnss import read_event_schedule, read_topology
  File "/usr/local/lib/python2.7/dist-packages/fnss/**init**.py", line 36, in <module>
    from fnss.topologies import *
  File "/usr/local/lib/python2.7/dist-packages/fnss/topologies/**init**.py", line 4, in <module>
    from fnss.topologies.datacenter import *
  File "/usr/local/lib/python2.7/dist-packages/fnss/topologies/datacenter.py", line 7, in <module>
    import networkx as nx
  File "/usr/local/lib/python2.7/dist-packages/networkx/**init**.py", line 87, in <module>
    import networkx.readwrite
  File "/usr/local/lib/python2.7/dist-packages/networkx/readwrite/**init**.py", line 14, in <module>
    from networkx.readwrite.gml import *
  File "/usr/local/lib/python2.7/dist-packages/networkx/readwrite/gml.py", line 46, in <module>
    from lib2to3.refactor import RefactoringTool
  File "/usr/lib/python2.7/lib2to3/refactor.py", line 27, in <module>
    from .fixer_util import find_root
  File "/usr/lib/python2.7/lib2to3/fixer_util.py", line 9, in <module>
    from .pygram import python_symbols as syms
  File "/usr/lib/python2.7/lib2to3/pygram.py", line 32, in <module>
    python_grammar = driver.load_grammar(_GRAMMAR_FILE)
  File "/usr/lib/python2.7/lib2to3/pgen2/driver.py", line 113, in load_grammar
    logger = logging.getLogger()
AttributeError: 'module' object has no attribute 'getLogger'
PLOTTING RESULTS
[PLOT] Plotting cache hit ratio vs alpha
Traceback (most recent call last):
  File "plot.py", line 312, in <module>
    main()
  File "plot.py", line 98, in main
    plot_chr_alpha_sensitivity()
  File "plot.py", line 124, in plot_chr_alpha_sensitivity
    S = SummaryAnalyzer(path.join(SUMMARY_LOG_DIR, 'SUMMARY_CACHE_HIT_RATIO.txt'))
  File "/home/namtt/Downloads/hashrouting/icarus/analysis.py", line 19, in __init__
    self.data = genfromtxt(summary_file, dtype=None, delimiter='\t', names=True)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1451, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rbU'))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 151, in open
    return ds.open(path, mode)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/_datasource.py", line 501, in open
    raise IOError("%s not found." % path)
IOError: /home/namtt/Downloads/hashrouting/logs/SUMMARY_CACHE_HIT_RATIO.txt not found.
DONE

**Comment by lorenzosaino** [comment]
Hi,

Some other user reported that issue before. I think this is due to an API change in a recent version of the NetworkX package.

Could you please tell me what version of NetworkX are you using? Try downgrading NetworkX to version 1.7. That should work.

Finally, let me point out that this version of Icarus is no longer maintained. This should be used only to reproduce the results of the ICN'13 hashrouting paper. If you wish to make further experiments, you should use the code in the main Icarus repository.

Please let me know if this fixes it.

Lorenzo

**Comment by technickid** [comment]
hi, sorry for troubling you.
my networkx version is 1.6-2 and it still not fixed. 

Package: python-networkx
Status: install ok installed
Priority: optional
Section: python
Installed-Size: 2594
Maintainer: Ubuntu Developers ubuntu-devel-discuss@lists.ubuntu.com
Architecture: all
Version: 1.6-2
Depends: python (>= 2.6), python-support (>= 0.90.0)

**Comment by lorenzosaino** [comment]
This is very strange. I had a look at the source code of NetworkX 1.6 and the code in the error output you sent me does not match with the actual source code.

I would proceed by trying to install NetworkX 1.7 from `pip` rather than using the Ubuntu package. Hopefully that fixes it.

**Comment by technickid** [comment]
It works. I have uninstalled networkx and installed new networkx 1.7 by pip.

Thank you!

**Comment by lorenzosaino** [comment]
Great to hear that! Good luck with your research!
